/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_develop_hua_jni_MainActivity */

#ifndef _Included_com_develop_hua_jni_MainActivity
#define _Included_com_develop_hua_jni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_develop_hua_jni_MainActivity
 * Method:    createStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_develop_hua_jni_MainActivity_createStrFromJni
  (JNIEnv *env, jobject){
    return env->NewStringUTF("ndk-build jni");
}

#ifdef __cplusplus
}
#endif
#endif
